### ISSUE TITLE
[CKAN] Outdated "Home page"

### ISSUE THREAD

**Issue by SunSerega** [KSP2Community/PatchManager#20]
CKAN still shows this as this mod's "Home page": https://github.com/KSP2Community/PatchManager/wiki

**Comment by jan-bures** [comment]
![image](https://github.com/KSP2Community/PatchManager/assets/2668168/cf8a1412-a3f2-4413-ab6f-1f8c28ca2af3)
I can see the correct page in CKAN. You may just need to let it stay open for a bit for it to update, since it has to refresh the information from SpaceDock.
