### ISSUE TITLE
unable to patch resource recipes

### ISSUE THREAD

**Issue by KSRe-dev** [KSP2Community/PatchManager#29]
resources work as expected, but recipes can't be accessed
```
:resources #Methalox {
	displayNameKey: "Resource/DisplayName/Methane";
}
:resources #Oxidizer {
	displayNameKey: "Resource/DisplayName/Methane";
}
```

```
[Info   :   Console] Patching resources:methalox
[Info   :   Console] Field does not exist :3
[Info   :   Console] Patched resources:methalox with 1 patches. Total: 157
...
[Info   :   Console] Patching resources:Oxidizer
[Info   :   Console] Patched resources:Oxidizer with 1 patches. Total: 158
```

using ```:resources .recipe { ... }``` has the same result

**Comment by cheese3660** [comment]
Could you hand me the cached Methalox json file in the patch manager cache?

**Comment by cheese3660** [comment]
Scratch that, I see the issue

**Comment by cheese3660** [comment]
```
:resources #Methalox > #methane {
}
```

**Comment by cheese3660** [comment]
Though i may have gotten the capitalization wrong

**Comment by cheese3660** [comment]
> yep thats great
> 
> lastly, how can we add a new recipe? as the `isRecipe` flag is above the data object in the addressables and this seems to be a different class, im unsure how to define that inside `:resources`
```scss
@new("RecipeName",true)
:resources {
}
```
