### ISSUE TITLE
Issue when removing all resource containers from crew pods

### ISSUE THREAD

**Issue by ghost** [KSP2Community/PatchManager#33]
**Summary:** errors and issues when all resource containers are removed from crew pods

**Reproduction:** Remove both electric charge and monopropellant from a crew pod, e.g.

```
:parts #pod_1v_conical_crew {
  * > resourceContainers > .MonoPropellant { @delete; }
  * > resourceContainers > .ElectricCharge { @delete; }
}
```
This seems to be applied as expected in the cache:
```  "resourceContainers": [ ],```

**Isolation:** Removed the patch to keep at least one resource on the crew pod and everything returns to normal

**Issues:** When first selecting the pod it's just a purple circle without the model, this error appears in console:

![image](https://github.com/KSP2Community/PatchManager/assets/152925960/c6d664c5-3b65-4684-aa9d-49a6274e194e)

After removing the pod and then trying to add it to a vessel after this, nothing appears when clicking on the part icon, and these errors are spammed in console (every FixedUpdate):

![image](https://github.com/KSP2Community/PatchManager/assets/152925960/315c673d-7f47-4e4a-a4e9-b0b6cb6778ce)

After going through this process I think the bug may be on the backend instead of just a syntax or user issue

**Comment by cheese3660** [comment]
You need to remove the module_resourcecapacities as well
